name: example
description: Draggable Menu Example.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  draggable_menu:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
